SIR_NAMES = [
    "Silva","Santos","Oliveira","Pereira","Costa","Rodrigues","Alves","Lima","Gomes","Ribeiro",
    "Martins","Araújo","Rocha","Fernandes","Azevedo","Teixeira","Moreira","Barros","Freitas","Nogueira",
    "Guimarães","Batista","Cunha","Farias","Rangel","Pacheco","Lopes","Macedo","Borges","Miranda",
    "Monteiro","Carneiro","Cavalcante","Tavares","Coelho","Bezerra","Paiva","Viana","Dantas","Lacerda",
    "Figueiredo","Neves","Pinheiro","Braga","Torres","Queiroz","Guedes","Menezes","Rios","Amorim",
    "Cardoso","Correia","Pimentel","Abreu","Assis","Peixoto","Magalhães","Siqueira","Xavier","Falcão",
    "Goulart","Beltrão","Holanda","Brito","Rezende","Maia","Campos","Lins","Barreto","Caldas",
    "Coutinho","Nascimento","Medeiros","Portela","Cabral","Seabra","Valente","Antunes","Pontes","Rabelo",
    "Furtado","Gusmão","Chaves","Sarmento","Leite","Pires","Franco","Albuquerque","Arruda","Sampaio",
    "Bittencourt","Lobato","Malheiros","Andrada","Junqueira","Mascarenhas","Seixas","Paes","Lobo","Werneck",
    "Mattos","Fialho","Soares","Neiva","Teles","Bragança","Sales","Loyola","Salgado","Trindade",
    "Loureiro","Resende","Alencar","Leitão","Mendonça","Barcellos","Serpa","Fonseca","Roriz","Damasceno",
    "Nóbrega","Severo","Veloso","Targino","Amaral","Póvoas","Lemos","Brandão","Louzada","Parente",
    "Sabino","Borba","Camargo","Gama","Salles","Azeredo","Peçanha","Mendanha","Barata","Tinoco",
    "Afonso","Pina","Sarzedas","Meirelles","Ferraz","Toledo","Gouveia","Bastos","Mota","Mello",
    "Leme","Belém","Lobão","Paixão","Simões","Salomão","Jordão","Quevedo","Veiga","Souza",
    "Fagundes","Trombini","Sartori","Bianchi","Rossi","Ferrari","De Luca","Colombo","Moretti","Greco",
    "Conti","Rinaldi","Esposito","Romano","Ricci","Lombardi","Schmidt","Müller","Weber","Schneider",
    "Aguiar","Almeida","Amarante","Anjos","Aragão","Arantes","Athayde","Avila","Bandeira","Belmonte",
    "Benites","Bernardes","Bicalho","Bonfim","Botelho","Braz","Breves","Bueno","Calegari","Canedo",
    "Carvalho","Casagrande","Castanheira","Castilho","Cerqueira","Chagas","Cipriano","Colares","Constante","Cordeiro",
    "Crispim","Damiani","Delgado","Drummond","Escobar","Esteves","Falcetti","Faria","Feliciano","Fialho",
    "Fleury","Fortes","Fragoso","França","Garcia","Gentil","Godoy","Granja","Grillo","Haddad",
    "Herculano","Horta","Ibrahim","Ilha","Jardim","Kleinubing","Kowalski","Lage","Leandro","Levi",
    "Libâneo","Linhares","Lourenço","Maciel","Maluf","Mangabeira","Marcondes","Marques","Masceno","Meira",
    "Mesquita","Milani","Moraes","Morato","Muniz","Navarro","Negreiros","Noronha","Novaes","Oliveira Neto",
    "Ornelas","Osório","Padilha","Padrão","Palhares","Paranhos","Paz","Pedrosa","Penha","Peregrino",
    "Pinto","Pó","Porto","Prado","Quadros","Quintana","Quirino","Ramalho","Ramos","Rebouças",
    "Ribeiro Neto","Righetto","Roncato","Sacramento","Saldanha","Santana","Saravia","Serrano","Sette","Silveira",
    "Sobral","Sodré","Spinelli","Tadini","Taques","Tavares Neto","Tenório","Uchoa","Urbano","Valadão",
    "Valença","Valladares","Vargas","Vasconcelos","Ventura","Vidal","Vieira","Villas Boas","Viterbo","Zamboni",

    # italianos
    "Andreoli","Baldini","Barbosa","Barichello","Bertolucci","Bonetti","Bortolotto","Brunetti","Callegari","Capello",
    "Cappellari","Carletti","Cattaneo","Ceccon","Cervi","Cipolla","Dal Bosco","Dallagnol","Dalto","De Bortoli",
    "De Marchi","Del Vecchio","Donati","Fabbri","Farinelli","Ferraro","Fioravanti","Galli","Gasperini","Giordani",
    "Grassi","Locatelli","Longo","Mancini","Marini","Mazzini","Molinari","Montanari","Morello","Paganini",
    "Pellegrini","Petrini","Raimondi","Rizzi","Sartorelli","Serafini","Testa","Toniolo","Venturi","Zanetti",
     "Abate","Accorsi","Agostini","Albertini","Alessandri","Amadei","Ambrosini","Anastasio","Angelini","Anselmi",
    "Antonelli","Armani","Arrigoni","Avanzini","Baglioni","Baldi","Bandini","Baraldi","Barbieri","Barone",
    "Bartolini","Bellini","Bellucci","Benedetti","Benetti","Bernardi","Bersani","Bianchi","Biondi","Bissoli",
    "Bocchi","Bonaccorsi","Bonfanti","Bonomi","Bordignon","Boschetti","Bottini","Brambilla","Brunello","Busato",
    "Cagnin","Calabrese","Campagnaro","Campanella","Canale","Canova","Capraro","Carbone","Caruso","Casagrandi",
    "Casali","Casarin","Cassano","Cattani","Cavalieri","Cazzaniga","Cecchini","Celli","Cerruti","Chiesa",
    "Cimino","Colombo","Comin","Conte","Coppola","Costa","Cremonese","Cristofoli","D'Agostino","D'Alessandro",
    "D'Amico","D'Angelo","D'Auria","Dalla Costa","Dalla Rosa","Dalla Torre","De Angelis","De Luca","De Martino","De Santis",
    "Di Benedetto","Di Carlo","Di Lorenzo","Di Marco","Di Mauro","Di Pietro","Donadelli","Donazzan","Esposito","Fabbro",
    "Facchini","Fadda","Falcone","Fantin","Fanton","Favaro","Ferrari","Ferraris","Ferronato","Ferro",
    "Filippi","Finocchiaro","Fiorini","Furlan","Gagliardi","Gallo","Garofalo","Gentile","Giacon","Giannini",
    "Giovannetti","Giuliani","Gobbi","Grimaldi","Grosso","Guidi","Landi","Lazzari","Leone","Lombardo",
    "Lucchesi","Maccari","Magnani","Malaguti","Manca","Marangon","Marchese","Marchetti","Marconi","Martini",
    "Massaro","Mazzucco","Meneghetti","Merlo","Messina","Milani","Minelli","Monti","Morandi","Moretti",
    "Moro","Nardelli","Neri","Orlando","Pagani","Palmieri","Parisi","Pavan","Pellegrino","Peretti",
    "Piazza","Piccoli","Piva","Poli","Pugliese","Raffaelli","Raimondo","Riccardi","Rinaldo","Romagnoli",
    "Rossi","Russo","Sala","Salvadori","Santini","Savio","Scalabrini","Scarpin","Serra","Sorrentino",
    "Spinosa","Stefanelli","Tarantino","Terranova","Tessaro","Tomasi","Tosi","Trevisan","Trentin","Valentini",
    "Vanzetto","Varani","Vecchi","Verdi","Veronese","Vicentini","Vignoli","Viola","Zago","Zambelli",
    "Zampieri","Zanin","Zanini","Zappia","Zecchin","Zeni","Zordan","Zorzi","Zuccaro","Zugno",

    # variações muito comuns no Brasil
    "Andreazza","Baggio","Balzan","Bellotto","Benincá","Bergamasco","Bresciani","Brigatti","Busnello","Caleffi",
    "Camatti","Canever","Capovilla","Casagrande","Dal Prá","Dal Pizzol","Dalla Vecchia","Fornasier","Giacomelli","Menon",
    "Pizzato","Sbrissa","Trevisol","Vettorazzi","Zago Neto","Zanchetta","Zanella","Zonatto","Zoppas","Zottis"

    # alemães / europeus
    "Albrecht","Arnold","Bauer","Bergmann","Brandt","Busch","Dietrich","Engel","Faber","Friedrich",
    "Geisler","Hahn","Hein","Henning","Keller","Koch","Krause","Lang","Lehmann","Maier",
    "Meier","Neumann","Otto","Paul","Pfeiffer","Reuter","Roth","Schaffer","Schmitt","Schulz",
    "Seidel","Vogel","Wagner","Walter","Zimmermann", "Ackermann","Adam","Adler","Albers","Altmann","Arnold","Bach","Baumann","Behr","Bender",
    "Berg","Biermann","Binder","Blank","Blum","Bohm","Brandner","Breuer","Brinkmann","Bruckner",
    "Brunner","Buchholz","Burg","Claus","Conrad","Daum","Deckert","Dengler","Diehl","Dorfman",
    "Drescher","Eberhardt","Eckert","Edelmann","Egger","Ehrlich","Eichhorn","Eisele","Engler","Ernst",
    "Faust","Feldmann","Fink","Franke","Franz","Freitag","Fuchs","Gärtner","Geiger","Graf",
    "Greiner","Gross","Gruber","Günther","Haase","Habermann","Hacker","Hagemann","Haller","Hartmann",
    "Hecht","Heidemann","Heil","Heinrich","Helbig","Heller","Herbst","Herrmann","Hesse","Hirsch",
    "Hoff","Hofmann","Holz","Hoppe","Horn","Huber","Jäger","Jahn","Kaiser","Kappel",
    "Kastner","Keil","Kern","Kiefer","Klinger","Klopfer","Knoll","Kopf","Kraft","Kramer",
    "Kunz","Kurz","Langner","Lenz","Licht","Lindner","Lorenz","Ludwig","Maas","Mayer",
    "Merkel","Metzger","Meyer","Michel","Mohr","Moser","Nagel","Naumann","Nestler","Nickel",
    "Noll","Nowak","Ott","Pabst","Paulsen","Petermann","Pfaff","Pohl","Preiss","Reich",
    "Reinhardt","Renner","Riedel","Rieger","Ritter","Rohde","Rupp","Sauer","Schade","Schaller",
    "Schäfer","Schenk","Schindler","Schirmer","Schlegel","Schlosser","Schmalz","Schramm","Schubert","Schulte",
    "Schwab","Schwarz","Seifert","Senger","Siebert","Simon","Singer","Sommer","Stahl","Stein",
    "Steiner","Stoll","Straub","Sturm","Thiel","Tietz","Ulrich","Urban","Voigt","Volk",
    "Voss","Weidner","Weiss","Wendt","Wernicke","Westphal","Wiedemann","Wilhelm","Winter","Wirth",
    "Wolf","Wolff","Zeller","Ziegler","Zimmer","Zorn","Bastian","Berger","Bittner","Bloch",
    "Brenner","Brock","Buchner","Buschmann","Dietz","Dorner","Ebert","Endres","Fahr","Fechner",
    "Fischer Neto","Fritsch","Glaser","Glock","Grimm","Hahn","Hummel","Jacobs","Jost","Kopp",
    "Kuhl","Lechner","Lehner","Marquardt","Mathis","Niemann","Pfeffer","Reuter","Roemer","Sattler",
    "Scholz","Schroeder","Seiler","Spengler","Stock","Theis","Trautmann","Vogelmann","Wacker","Zwick"

    # espanhóis / latino-americanos
    "Acuña","Benavides","Carrasco","Dominguez","Escudero","Gallardo","Herrera","Iglesias","Medina","Mendoza",
    "Montoya","Paredes","Salazar","Santiago","Sepúlveda","Zamora", "Aguilar","Aguirre","Alarcón","Alba",
    "Albornoz","Alcántara","Aldana","Alonso","Altamirano","Álvarez",
    "Amaya","Andrade","Angulo","Aparicio","Aranda","Arellano","Arenas","Arriaga","Arroyo","Astorga",
    "Ávila","Ayala","Baeza","Balboa","Barahona","Barajas","Barrera","Barrios","Batista","Beltrán",
    "Benítez","Bernal","Blanco","Bolívar","Bonilla","Borja","Bravo","Burgos","Bustamante","Caballero",
    "Cabrera","Calderón","Calvo","Camacho","Cano","Cárdenas","Carmona","Carrera","Casas","Castellanos",
    "Castillo","Castro","Ceballos","Cervantes","Chávez","Cifuentes","Collado","Colmenares","Contreras","Cortés",
    "Cuenca","Cuevas","Delgado","Díaz","Durán","Echeverría","Encinas","Enríquez","Espinosa","Esteban",
    "Estrada","Fajardo","Ferrer","Flores","Fonseca","Franco","Fuentes","Gaitán","Galindo","Gálvez",
    "García","Giménez","Godínez","Granados","Guerrero","Guzmán","Hernández","Hidalgo","Hinojosa","Huerta",
    "Ibarra","Infante","Jaime","Jaimes","Jaramillo","Jiménez","Juárez","Lara","Leiva","Linares",
    "Lira","Lobato","Lozano","Lucero","Maldonado","Manrique","Márquez","Mata","Matamoros","Mejía",
    "Meléndez","Merino","Molina","Moncada","Montero","Morales","Moreno","Moya","Muñoz","Navarrete",
    "Navarro","Núñez","Ocampo","Ojeda","Oliva","Ordoñez","Ortega","Ortiz","Osuna","Padilla",
    "Palacios","Palma","Paniagua","Parra","Patiño","Peña","Peralta","Pérez","Pineda","Plata",
    "Ponce","Portillo","Posada","Prieto","Puente","Quezada","Quijano","Quintero","Ramírez","Rangel",
    "Reyes","Rico","Ríos","Rivera","Robledo","Robles","Rocha","Rodríguez","Roldán","Romero",
    "Rosales","Rubio","Ruiz","Saavedra","Salgado","Sandoval","Santacruz","Sarmiento","Segovia","Serrano",
    "Sierra","Solano","Soria","Soto","Suárez","Téllez","Terán","Toledo","Toro","Trejo",
    "Trujillo","Ulloa","Urbina","Valdés","Valdivia","Valenzuela","Vargas","Vázquez","Vega","Velasco",
    "Vera","Vicente","Vidal","Yáñez","Zárate","Zavala","Zúñiga",

    # variações muito comuns na América Latina
    "Acevedo","Alfaro","Amador","Arévalo","Bermúdez","Castañeda","Coronado","Escobar","Figueroa","Gallardo Neto",
    "Henríquez","Ledezma","Miramontes","Mondragón","Olmedo","Peñaloza","Rentería","Santamaría","Vallejo","Villalobos",

    # compostos e formas frequentes
    "De la Cruz","De la Rosa","Del Valle","Del Río","Sanabria","Santa Cruz","San Martín","San Román",
    "Villanueva","Villarreal","Villaseñor","Villavicencio","Monteverde","Buenrostro","Camposano","Puig","Ribas"

    # árabes
    "Abdalla","Abdallah","Assad","Boulos","Farah","Habib","Kanaan","Khalil","Mansur","Nasser",
    "Saad","Said","Suleiman", "Abbas","Abbud","Abdoun","Abrahão","Adib","Affonso","Afiune","Ahmad","Aita","Akra",
    "Alam","Alawi","Ali","Amaral","Amim","Amorim","Anan","Anis","Antoun","Aouad",
    "Aoun","Arabi","Aramouni","Arida","Asfour","Atalla","Azzam","Azzi","Badawi","Badr",
    "Baghdadi","Bakir","Barakat","Barbosa","Bassil","Bayeh","Bazzi","Bechara","Beirute","Bichara",
    "Bitar","Boulos Neto","Brahim","Boutros","Braga","Canaan","Chahine","Chalhub","Chamas","Chami",
    "Chbib","Chebel","Chehade","Chehadi","Cheikh","Chucri","Chufani","Cury","Daoud","Darwich",
    "Deeb","Dib","Diniz","Dora","Douek","Elias","Elie","Estephan","Fadel","Fahd",
    "Fahed","Fakhoury","Fares","Farraj","Fattal","Fayad","Fayez","Feghali","Ferreira","Figueiredo",
    "Frangieh","Freitas","Gaber","Ganim","Gerges","Ghazal","Ghassan","Ghazzi","Ghosn","Gibran",
    "Habchi","Haddad","Hadid","Hage","Hajj","Hakim","Halabi","Hamdan","Hanna","Harb",
    "Hasan","Hatem","Helou","Henrique","Hikmat","Hobeika","Houri","Ibrahim","Ibrahin","Ilyas",
    "Iskandar","Issa","Jabbour","Jamil","Jardali","Jbara","Jebara","Jibrail","Jirjis","Jorge",
    "Kabbani","Kader","Kalil","Karam","Kassab","Kassir","Khairallah","Khater","Khoury","Kfoury",
    "Khalaf","Khatib","Kheir","Khouzam","Koury","Labaki","Lahoud","Latif","Lebbos","Leila",
    "Lotfi","Maalouf","Madi","Mahfouz","Malek","Mansour","Maroun","Massad","Matta","Mazin",
    "Medeiros","Mikhael","Milad","Moisés","Mourad","Moussa","Mufarrej","Nacif","Nader","Nahas",
    "Najjar","Nassif","Neme","Nehme","Nicolas","Noujaim","Obeid","Odeh","Omar","Oweiss",
    "Pacha","Pereira","Qasem","Qassab","Qattan","Rached","Rahme","Rameh","Rashid","Rezende",
    "Riad","Ribeiro","Rizk","Roumi","Saba","Sabbagh","Sader","Safadi","Salame","Salem",
    "Saliba","Salim","Salloum","Samaha","Samaan","Samir","Sarkis","Seif","Selim","Semaan",
    "Serhan","Shadid","Shahin","Shaker","Sharif","Shibli","Shukr","Sleiman","Slim","Souza",
    "Tahan","Taleb","Tamer","Tannous","Tarabay","Tayeh","Toufic","Trad","Trabulsi","Turra",
    "Yacoub","Yamin","Yared","Yazbek","Youssef","Zaher","Zaidan","Zein","Zoghbi","Zouain",
    "Zreik","Zuba","Zughbi","Zurayk","Abou Daher","Abou Fadel","Abou Jaoude","Abou Jamra","Abou Khalil","Abou Mourad",
    "Abou Nader","Abou Saleh","Abou Sleiman","Abou Zeid","Al Hajj","Al Najjar","Al Salame","Al Zaher","Beitune","Bou Assi",
    "Bou Habib","Bou Khalil","Bou Malhab","Bou Rached","Bou Saab","Dargham","El Khatib","El Khoury","El Zoghbi",
    "Ibn Saud","Ibn Sina","Ibn Youssef","Khaled","Mahmoud","Mustafa","Nabil","Rami","Sami","Walid"

    # japoneses (bem comuns no Brasil)
    "Aoki","Endo", "Akiyama","Fujimoto","Fukuda","Hasegawa","Hayashi","Honda","Ishida","Ito","Kaneko",
    "Kawasaki","Kobayashi","Matsuda","Matsumoto","Miyazaki","Morita","Nakagawa","Nakamura","Nishimura","Oda",
    "Okamoto", "Sato", "Saito","Sasaki","Shimizu","Sugimoto","Suzuki","Takeda","Tanaka","Ueda","Watanabe",
    "Yamamoto","Yamaguchi","Yamada", "Yasunaka", "Abe","Adachi","Aihara","Aizawa","Akagi","Akama","Amano","Anzai","Arai","Arakawa",
    "Asano","Ashida","Baba","Bando","Chiba","Chinen","Date","Deguchi","Doi","Ebihara",
    "Eguchi","Enomoto","Fujii","Fujita","Fukui","Fukunaga","Furukawa","Goda","Goto","Haga",
    "Hamada","Hamano","Hara","Harada","Hase","Hasebe","Hattori","Higa","Hirano","Hirata",
    "Hirose","Hiruma","Hiyama","Honma","Ichikawa","Igarashi","Iida","Iijima","Ikeda","Imai",
    "Imamura","Inaba","Inagaki","Inoue","Irie","Ishii","Ishikawa","Ishimoto","Itagaki","Iwasaki",
    "Izumi","Kagawa","Kaji","Kakizaki","Kamei","Kanai","Kanazawa","Kanda","Kanno","Kawaguchi",
    "Kawamura","Kawano","Kido","Kikuchi","Kimura","Kinoshita","Kiryu","Kishi","Kitagawa","Kitao",
    "Kiyota","Koike","Kojima","Kondo","Kubo","Kumagai","Kurata","Kuroda","Machida","Maeda",
    "Makino","Maruyama","Masuda","Matsui","Matsuoka","Matsuzaki","Mihara","Miki","Minami","Mineno",
    "Mitsui","Miura","Mizoguchi","Mizuno","Mochizuki","Mori","Morikawa","Morishita","Murakami","Murata",
    "Nagano","Nagata","Nagai","Nakajima","Nakano","Nakao","Nakayama","Namiki","Nara","Narita",
    "Nihei","Ninomiya","Nitta","Noguchi","Nonaka","Obata","Ogata","Ogawa","Ogiwara","Ohashi",
    "Oishi","Ojima","Okada","Okazaki","Okumura","Onishi","Onodera","Osawa","Oshima","Ota",
    "Otani","Oyama","Sakaguchi","Sakai","Sakakibara","Sakamoto","Sano","Sawada","Sekiguchi","Sekine",
    "Sendai","Shibata","Shiga","Shimada","Shinohara","Shiozaki","Shirakawa","Shiratori","Shoda","Sonoda",
    "Sugawara","Sugiyama","Suzumura","Tabata","Tachibana","Tada","Taguchi","Takahashi","Takano","Takashima",
    "Takayama","Takeuchi","Tamura","Taniguchi","Tatsumi","Terada","Toda","Tokuda","Tomita","Torii",
    "Toyama","Tsuboi","Tsuda","Tsukamoto","Uchida","Ueno","Umehara","Uno","Usui","Wada",
    "Wakayama","Yagi","Yahata","Yajima","Yamasaki","Yanagida","Yanagisawa","Yano","Yasuda","Yokoi",
    "Yokota","Yokoyama","Yoshida","Yoshikawa","Yoshimura","Yoshino","Yoshizawa","Yuda","Yui","Yukawa",

    # menos comuns, mas reais e registrados
    "Akutsu","Aoyagi","Bessho","Fukazawa","Furuta","Horiguchi","Ichimura","Ishizaki","Kadota","Kawabata",
    "Koyama","Masaki","Mochida","Morimoto","Nakamoto","Nishida","Odaka","Suganuma","Takigawa","Yamadaira"
]


